# Generated by Django 4.1.7 on 2023-03-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.ingredient'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('batch_size_l', models.FloatField(default=0)),
                ('comments', models.CharField(max_length=1000)),
                ('yeast', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='HopRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.IntegerField(default=0)),
                ('time_min', models.IntegerField(default=0)),
                ('dry_hop', models.BooleanField(default=False)),
                ('hop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.hop')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='GrainRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.IntegerField(default=0)),
                ('grain', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.grain')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.recipe')),
            ],
        ),
    ]
