# Generated by Django 4.1.7 on 2023-03-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_ingredient_recipe_hoprecipe_grainrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='yeast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stock.ingredient'),
        ),
    ]
