# Generated by Django 4.1.7 on 2023-03-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_recipe_yeast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
