# Generated by Django 4.1.7 on 2023-03-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_recipe_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mash_temperature_c',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brew_date', models.DateTimeField()),
                ('bottling_date', models.DateTimeField()),
                ('measured_og', models.FloatField(default=1)),
                ('measured_fg', models.FloatField(default=1)),
                ('measured_mash_ph', models.FloatField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.recipe')),
            ],
        ),
    ]
