# Generated by Django 4.1.7 on 2023-03-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_recipe_mash_temperature_c_brew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='bottling_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='brew',
            name='brew_date',
            field=models.DateTimeField(null=True),
        ),
    ]
