# Generated by Django 4.1.7 on 2023-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_brew_bottling_date_alter_brew_brew_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='owner',
            field=models.CharField(default='root', max_length=200),
            preserve_default=False,
        ),
    ]
