# Generated by Django 4.1.7 on 2023-03-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_brew_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='state',
            field=models.CharField(choices=[('Prep', 'Prep'), ('Brewing', 'Brewing'), ('Fermenting', 'Fermenting'), ('Completed', 'Completed')], default='Prep', max_length=20),
        ),
    ]
