# Generated by Django 4.1.7 on 2023-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_brew_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='evaporation_lph',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='brew',
            name='mash_thickness_lpkg',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='brew',
            name='measured_mash_temp_c',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='brew',
            name='pre_boil_gravity',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='brew',
            name='pre_boil_volume_l',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='brew',
            name='sparge_water_temp_c',
            field=models.FloatField(default=72),
        ),
        migrations.AddField(
            model_name='recipe',
            name='boil_time_min',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='brew',
            name='bottling_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='brew',
            name='brew_date',
            field=models.DateField(null=True),
        ),
    ]
