# Generated by Django 4.1.7 on 2023-03-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_brew_bottling_date_alter_brew_brew_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brew',
            old_name='sparge_water_temp_c',
            new_name='mash_out_temp_c',
        ),
    ]
