# Generated by Django 4.1.7 on 2023-03-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_rename_sparge_water_temp_c_brew_mash_out_temp_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='fermenter_volume_l',
            field=models.FloatField(default=0),
        ),
    ]
