# Generated by Django 4.1.7 on 2023-03-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_brew_fermenter_volume_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='bottling_volume_l',
            field=models.FloatField(default=0),
        ),
    ]
