# Generated by Django 4.1.7 on 2026-04-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
        ('stock', '0017_brew_ingredients_consumed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brew',
            name='brew_monitor_link',
        ),
        migrations.AddField(
            model_name='brew',
            name='project_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.project'),
        ),
    ]
