# Generated by Django 4.1.7 on 2026-04-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
        ('stock', '0018_remove_brew_brew_monitor_link_brew_project_monitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brew',
            name='project_monitor',
        ),
        migrations.AddField(
            model_name='brew',
            name='monitor_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.project'),
        ),
    ]
