# Generated by Django 4.1.7 on 2026-04-24 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def link_owners(apps, schema_editor):
    # Get the models and the User model
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    
    for model_name in ['Brew', 'Recipe', 'Stock']:
        Model = apps.get_model('stock', model_name)
        for obj in Model.objects.all():
            # Try to find a user with the username matching the old string
            user = User.objects.filter(username=obj.owner_old).first()
            if user:
                obj.owner = user
                obj.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0019_remove_brew_project_monitor_brew_monitor_project'),
    ]

    operations = [
        # 1. Rename old char fields
        migrations.RenameField('Brew', 'owner', 'owner_old'),
        migrations.RenameField('Recipe', 'owner', 'owner_old'),
        migrations.RenameField('Stock', 'owner', 'owner_old'),

        # 2. Add new ForeignKey fields (temporarily allow null so we can fill them)
        migrations.AddField(
            model_name='brew',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),

        # 3. Run the data migration
        migrations.RunPython(link_owners),

        # 4. Remove the old fields
        migrations.RemoveField('Brew', 'owner_old'),
        migrations.RemoveField('Recipe', 'owner_old'),
        migrations.RemoveField('Stock', 'owner_old'),
    ]
