ServerName localhost
ServerAdmin jordan038@gmail.com
DocumentRoot /var/www/html
WSGIPythonPath /var/www/html
WSGIScriptAlias / /var/www/html/core/wsgi.py
WSGIDaemonProcess brew-monitor processes=1 threads=1 python-path=/usr/local/lib/python3.9/site-packages home=/var/www/html
WSGIProcessGroup brew-monitor
<Directory "/var/www/html">
Require all granted
</Directory>
